(DSP-1033) reposition list nodes
dasch-swiss/dsp-api pull request #1764
Opened 2020-11-26 18:58 UTC by SepidehAlassi

resolves DSP-

2020-11-27 10:38 UTC, benjamingeer approved these changes
This looks great. Please try reformatting these files using the [dsp-intellij-settings](https://github.com/dasch-swiss/dsp-intellij-settings) repo that I've just made.

2020-11-27 10:38 UTC, benjamingeer commented on webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
> +                throw BadRequestException(s"Invalid position given, maximum allowed is=${numberOfChildren + 1}!")
Maybe this is just me, but I don't like receiving error messages with exclamation marks in them, it makes me feel like the computer is shouting at me. :)

2020-11-27 10:38 UTC, benjamingeer commented on webapi/src/main/scala/org/knora/webapi/responders/admin/ListsResponderADM.scala
> +         * Checks that the position of the node is updated and node is sublist of specified parent.
Please finish the `@throws` comment.

2020-11-27 10:40 UTC, benjamingeer commented
Did I review this by mistake? I thought I had got a review request but maybe I didn't. :)

2020-11-30 13:24 UTC, benjamingeer requested changes
This is even better than the first time I reviewed it. :) But please reformat it with the shared IntelliJ settings.

2020-11-30 15:02 UTC, SepidehAlassi commented
> This is even better than the first time I reviewed it. :) But please reformat it with the shared IntelliJ settings.

I have reformatted it already :/

2020-11-30 16:57 UTC, benjamingeer commented
> I have reformatted it already :/

I've just done commit b056bb2 so you can see what `Reformat Code` does in my IntelliJ with that config.

2020-11-30 16:59 UTC, benjamingeer commented
Hmm but I don't like what it did here:

```scala
            sparqlQuery <- Future(org.knora.webapi.messages.twirl.queries.sparql.admin.txt.getListNode(
                triplestore = settings.triplestoreType,
                nodeIri = nodeIri
            ).toString())
            ).toString()
            )
```

I wanted it to look like this:

```scala
            sparqlQuery <- Future(
                org.knora.webapi.messages.twirl.queries.sparql.admin.txt.getListNode(
                    triplestore = settings.triplestoreType,
                    nodeIri = nodeIri
                ).toString()
            )
```

2020-12-01 08:42 UTC, benjamingeer approved these changes
I've fixed the formatting in `ListsResponderADM` manually, and changed the settings repository to hopefully produce better results.

2020-12-01 10:08 UTC, SepidehAlassi commented
> I've fixed the formatting in `ListsResponderADM` manually, and changed the settings repository to hopefully produce better results.

thank you very much for reformatting the code and for reviewing this PR.

2020-12-01 10:24 UTC, subotic commented
@SepidehAlassi @benjamingeer I think that it should be possible to store all settings inside https://github.com/dasch-swiss/dsp-api/blob/main/.editorconfig. The EditorConfig plugin comes bundled with IntelliJ. This would also allow, other IDEs to be configured correctly.

2020-12-01 10:25 UTC, subotic approved these changes
Thanks, looks great!

2020-12-01 12:31 UTC, merged