feat(listsADM): add canDeleteList route
dasch-swiss/dsp-api pull request #1968
Opened 2021-12-14 17:19 UTC by mpro7

resolves DEV-145

2021-12-16 08:32 UTC, irinaschubert approved these changes
LGTM, just some suggestions regarding naming.

2021-12-16 08:32 UTC, irinaschubert commented on webapi/src/main/scala/org/knora/webapi/routing/admin/lists/DeleteListItemsRouteADM.scala
> +   * Checks if a list (and its children) is unused and if can be deleted.
```suggestion
   * Checks if a list (and its children) can be deleted. This is the case if none of its nodes is used in data.
```

2021-12-16 08:32 UTC, irinaschubert commented on webapi/src/main/scala/org/knora/webapi/routing/admin/lists/DeleteListItemsRouteADM.scala
> +          stringFormatter.validateAndEscapeIri(iri, throw BadRequestException(s"Invalid param list IRI: $iri"))
```suggestion
          stringFormatter.validateAndEscapeIri(iri, throw BadRequestException(s"Invalid list IRI: $iri"))
```

2021-12-16 08:32 UTC, irinaschubert commented on webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/canDeleteList.scala.txt
> + * Checks if a list (and its children) is unused and if can be deleted.
```suggestion
 * Checks if a list (and its children) is used in data.
```

2021-12-16 08:32 UTC, irinaschubert commented on webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/canDeleteList.scala.txt
> +  BIND(IRI("@listIri") AS ?nodeToBeDeleted)
```suggestion
  BIND(IRI("@listIri") AS ?nodeToBeChecked)
```

2021-12-16 08:32 UTC, irinaschubert commented on webapi/src/main/twirl/org/knora/webapi/messages/twirl/queries/sparql/admin/canDeleteList.scala.txt
> +    ?nodeToBeDeleted knora-base:hasSubListNode* ?subNode .
```suggestion
    ?nodeToBeChecked knora-base:hasSubListNode* ?subNode .
```

2021-12-16 09:02 UTC, BalduinLandolt approved these changes
looks good... I aggree with Irina's naming suggestions, and there is one typo (`unused` instead of `used`), but apart from that all fine

2021-12-16 10:10 UTC, subotic requested changes

2021-12-16 10:10 UTC, subotic commented on webapi/src/test/scala/org/knora/webapi/responders/admin/ListsResponderADMSpec.scala
> +      "return FALSE for a node that is unused but has a child which is used" in {
`node` -> `listIri`

2021-12-17 16:47 UTC, subotic approved these changes

2021-12-17 16:48 UTC, subotic commented
@mpro7 thanks, looks good now.

2021-12-17 18:29 UTC, merged