refactor: remove Redis related implementation leftovers (DEV-1503)
dasch-swiss/dsp-api pull request #2290
Opened 2022-11-18 14:23 UTC by mpro7

Issue Number: DEV-1503

## Pull Request Checklist

### Basic Requirements

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

- [ ] Bugfix: represents bug fixes
- [ ] Refactor: represents production code refactoring
- [ ] Feature: represents a new feature
- [ ] Documentation: documentation changes (no production code change)
- [ ] Chore: maintenance tasks (no production code change)
- [ ] Style: styles updates (no production code change)
- [ ] Test: all about tests: adding, refactoring tests (no production code change)
- [ ] Other... Please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No

### Does this PR change client-test-data?

- [ ] Yes (don't forget to update the JS-LIB team about the change)
- [ ] No

### Other information

2022-11-18 15:09 UTC, BalduinLandolt approved these changes
LGTM

2022-11-18 15:13 UTC, irinaschubert requested changes
There are more occurences of Redis floating around, I was just working sth in the configuration (AppConfig and application.conf) and in there is Redis related stuff, too. Also in the docs, probably.

I would suggest to also take the word "cache" into the PR title (in case we search for it in the future).

2022-11-21 16:43 UTC, BalduinLandolt approved these changes
LGTM

2023-01-02 10:43 UTC, irinaschubert approved these changes

2023-01-02 14:37 UTC, seakayone approved these changes

2023-01-02 14:41 UTC, merged