refactor: ziofy usersresponderv1 (DEV-1750)
dasch-swiss/dsp-api pull request #2478
Opened 2023-02-24 13:53 UTC by mpro7

## Pull Request Checklist

### Task Description/Number

Issue Number: DEV-1750

### Basic Requirements

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

- [ ] fix: represents bug fixes
- [ ] refactor: represents production code refactoring
- [ ] feat: represents a new feature
- [ ] docs: documentation changes (no production code change)
- [ ] chore: maintenance tasks (no production code change)
- [ ] test: all about tests: adding, refactoring tests (no production code change)
- [ ] other... Please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No
- [ ] Maybe (not 100% sure => check with FE)

### Does this PR change client-test-data?

- [ ] Yes (don't forget to update the JS-LIB team about the change)
- [ ] No

2023-02-24 14:03 UTC, irinaschubert approved these changes
LGTM

2023-02-24 14:58 UTC, seakayone approved these changes

2023-02-24 16:35 UTC, seakayone requested changes

2023-02-24 16:35 UTC, seakayone commented on webapi/src/main/scala/org/knora/webapi/responders/v1/UsersResponderV1.scala
> +            .as(PermissionsDataADM())
This line is causing your some test to fail. You should remove it.

Basically this line tells to ignore response the relay and replaces both success and failure by an empty `PermissionDataADM()`.

2023-02-27 07:38 UTC, seakayone approved these changes

2023-02-27 08:23 UTC, merged