wip
dasch-swiss/dsp-api pull request #2494
Opened 2023-03-01 08:21 UTC by mpro7

## Pull Request Checklist

### Task Description/Number

Issue Number: DEV-

### Basic Requirements

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

- [ ] fix: represents bug fixes
- [ ] refactor: represents production code refactoring
- [ ] feat: represents a new feature
- [ ] docs: documentation changes (no production code change)
- [ ] chore: maintenance tasks (no production code change)
- [ ] test: all about tests: adding, refactoring tests (no production code change)
- [ ] other... Please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No
- [ ] Maybe (not 100% sure => check with FE)

### Does this PR change client-test-data?

- [ ] Yes (don't forget to update the JS-LIB team about the change)
- [ ] No

2023-03-03 15:38 UTC, BalduinLandolt reviewed
see my comment on the ValuesResponderV2 trait

2023-03-03 15:38 UTC, BalduinLandolt commented on webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
> +final case class ValuesResponderV2Live(
can this be right that there is nothing in the trait?

2023-03-03 15:38 UTC, BalduinLandolt commented on webapi/src/main/scala/org/knora/webapi/responders/v2/ValuesResponderV2.scala
> +final case class ValuesResponderV2Live(
and shouldn't the `ValuesResponderV2Live` extend the trait?

2023-03-06 16:15 UTC, seakayone requested changes
Please fix tests first.

2023-03-17 07:57 UTC, closed without merging