add default value of projectRestrictedViewSize
dasch-swiss/dsp-api pull request #2873
Opened 2023-10-09 10:16 UTC by mpro7

## Pull Request Checklist

### Task Description/Number

Issue Number: DEV-2626

### Basic Requirements

Please check if your PR fulfills the following requirements:

- [ ] Tests for the changes have been added (for bug fixes / features)
- [ ] Docs have been added / updated (for bug fixes / features)

### PR Type

What kind of change does this PR introduce?

- [ ] fix: represents bug fixes
- [ ] refactor: represents production code refactoring
- [ ] feat: represents a new feature
- [ ] docs: documentation changes (no production code change)
- [ ] chore: maintenance tasks (no production code change)
- [ ] test: all about tests: adding, refactoring tests (no production code change)
- [ ] other... Please describe:

### Does this PR introduce a breaking change?

- [ ] Yes
- [ ] No
- [ ] Maybe (not 100% sure => check with FE)

### Does this PR change client-test-data?

- [ ] Yes (don't forget to update the JS-LIB team about the change)
- [ ] No

2023-10-09 12:15 UTC, BalduinLandolt approved these changes
LGTM

2023-10-10 15:46 UTC, seakayone requested changes

2023-10-10 15:46 UTC, seakayone commented on webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
> +    project <- projectRepo.findById(id).someOrFail(NotFoundException(s"Project '${getId(id)}' not found."))
Apart from this it looks good to me.

2023-10-10 15:48 UTC, seakayone commented on webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
> +    project <- projectRepo.findById(id).someOrFail(NotFoundException(s"Project '${getId(id)}' not found."))
In the responder you have already loaded the project, so there is also no need to query the database again here.

2023-10-11 11:30 UTC, seakayone commented on webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
> +    id: IriIdentifier,
This param is unused now, isn't it?

2023-10-11 11:44 UTC, mpro7 commented on webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
> +    project <- projectRepo.findById(id).someOrFail(NotFoundException(s"Project '${getId(id)}' not found."))
Thanks for your input. As we talked about in the responder only `ProjectADM` is exposed, thus it need an additional method that transform it into `KnoraProject`. Just for the recored :)

2023-10-11 11:45 UTC, mpro7 commented on webapi/src/main/scala/org/knora/webapi/slice/admin/domain/service/ProjectADMService.scala
> +    id: IriIdentifier,
Oh my lord 🙃 It should be fine now.

2023-10-11 12:06 UTC, merged