refactor: Use new RDF handling in more methods of project repo
dasch-swiss/dsp-api pull request #3032
Opened 2024-02-07 17:28 UTC by BalduinLandolt

## Pull Request Checklist

### Task Description/Number

Issue Number: DEV-

### PR Type

- [ ] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [ ] feat: represents new features
- [ ] fix: represents bug fixes
- [ ] perf: performance improvements
- [ ] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

### Does this PR change client-test-data?

- [ ] Yes

2024-02-15 18:20 UTC, BalduinLandolt commented
tests fail, will need some more work - sorry for premature review request

2024-02-16 18:52 UTC, seakayone requested changes

2024-02-16 18:52 UTC, seakayone commented on webapi/src/main/scala/org/knora/webapi/slice/admin/repo/rdf/Vocabulary.scala
> +    val belongsToOntology: Iri = Rdf.iri(KnoraAdminPrefixExpansion, "belongsToOntology")
I remember you wanted to remove this from the Vocabulary becuase it is just a "virtual" property in a single query.

2024-02-26 10:57 UTC, seakayone commented on webapi/src/main/scala/org/knora/webapi/slice/admin/repo/rdf/Vocabulary.scala
> +    val NS: Namespace = new SimpleNamespace("knora-base", KnoraBasePrefixExpansion)
The rdf4j vocabularies (e.g. for rdf, rdfs, foaf, ...) already have this as a naming convention, so I would vote for `NS`.

2024-02-26 10:59 UTC, seakayone approved these changes

2024-02-26 12:34 UTC, merged