feat: Add StandoffFootnoteTag (DEV-4306)
dasch-swiss/dsp-api pull request #3443
Opened 2024-12-11 19:03 UTC by siers

## Pull Request Checklist

### Task Description/Number

Issue Number: DEV-

### PR Type

- [ ] build/chore: maintenance tasks (no production code change)
- [ ] docs: documentation changes (no production code change)
- [ ] feat: represents new features
- [ ] fix: represents bug fixes
- [ ] perf: performance improvements
- [ ] refactor: represents production code refactoring
- [ ] test: adding or refactoring tests (no production code change)
- [ ] deprecated: Deprecation warning (ideally referencing a migration guide)

### Basic requirements for bug fixes and features

- [ ] Tests for the changes have been added
- [ ] Docs have been added / updated

### Does this PR introduce a breaking change?

- [ ] Yes

2024-12-28 12:33 UTC, BalduinLandolt approved these changes
Needs an ontology version bump to ensure the built-in ontologies are updated, otherwise it will not have any effect on existing servers.  
Other than that it looks good. Curious to see it in action! :)

2024-12-30 08:47 UTC, seakayone approved these changes

2024-12-30 08:51 UTC, seakayone commented
*question*: Would it make sense to document this feature?

https://docs.dasch.swiss/latest/DSP-API/02-dsp-ontologies/knora-base/#text-with-standoff-markup looks like a good place to me.

2024-12-30 08:59 UTC, seakayone reviewed
*question*: Would it make sense to document this feature?

https://docs.dasch.swiss/latest/DSP-API/02-dsp-ontologies/knora-base/#text-with-standoff-markup looks like a good place to me.

2024-12-30 09:02 UTC, seakayone submitted a review, later dismissed
*issue*: The changes do not have an effect

As @BalduinLandolt pointed out, we need to update the ontology version to ensure these changes are applied.

2025-01-02 08:09 UTC, mpro7 approved these changes

2025-01-07 07:31 UTC, BalduinLandolt requested changes
There is another issue with this PR: The current model does not allow for the `content` attribute that @derschnee68 has specified in DEV-4491.  
I think a test ensuring that it actually works as expected, would help here.

Another thing we need to discuss is how this model works with full text search. But this is a question for another place than the PR comment section.

2025-01-08 10:59 UTC, BalduinLandolt approved these changes
If CI passes, this should be good now.

2025-01-08 11:05 UTC, siers reviewed
Looks good.

2025-01-08 14:06 UTC, merged